backend:
  name: git-gateway
  branch: master

media_folder: "public/images/"
public_folder: "images/"

collections:
  - name: dogs
    label: Dogs
    folder: src/pages/dogs
    create: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/Article.astro",
        }
      - { label: "Dog Name", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - { label: "Featured Image", name: "featuredImg", widget: "image" }
      - {
          label: "Overall Score",
          name: "rating",
          widget: "number",
          required: true,
        }
      - { label: "Brand", name: "brand", widget: "string" }
      - {
          label: "Excerpt",
          name: "exceprt",
          widget: "string",
          required: true,
          pattern:
            ["^.{0,96}$", "Description cannot be more than 96 characters"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
